Update howtoresources.md
aws/aws-graviton-getting-started pull request #343
Opened 2023-11-14 19:03 UTC by sethfox

Added section for ### Development Tools

*Issue #, if available:*

*Description of changes:* added links to porting advisor and aperf to a new section call Developement Tools

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-15 14:39 UTC, lrbison requested changes
The link formatting is not correct and doesn't render well.  Can you please update it to `[Title](URL)` form?

2023-11-15 23:34 UTC, sethfox commented
Commit updated.

2023-11-16 14:41 UTC, AWSjswinney approved these changes

2023-11-16 14:42 UTC, lrbison approved these changes

2023-11-16 14:51 UTC, merged