tensorflow: update the userguide with the latest release details
aws/aws-graviton-getting-started pull request #387
Opened 2024-05-31 20:24 UTC by snadampal

TensorFlow deep learning container, wheel, and docker image details are updated. xla section is removed because the latest release integrated openXLA which requires changes in the build and usage. will update the userguide with XLA details once openXLA is validated on Graviton.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-06 21:16 UTC, provanshu commented
Thank you for looking into this. The clang and gcc builds work great!

2024-06-07 14:55 UTC, CristianPrundeanu commented on machinelearning/tensorflow.md
> +export PATH=/home/ubuntu/bazel/:$PATH
Minor: better to install bazel into the standard /usr/local/bin so you don't need to modify PATH every time
```
BAZEL=6.5.0  # modify version as needed
wget https://github.com/bazelbuild/bazel/releases/download/$BAZEL/bazel-$BAZEL-linux-arm64 -O /usr/local/bin/bazel
chmod +x /usr/local/bin/bazel
```

2024-06-07 15:24 UTC, RamaMalladiAWS commented on machinelearning/tensorflow.md
> +Starting from version 2.14.0, TensorFlow wheel enabled onednn+acl backend by default on Graviton CPUs which typically provides better performance than eigen backend. For previous versions of TensorFl
I would reword this sentence for better reading.
"On Graviton CPUs, onednn+acl is the default backend in TensorFlow v2.14.0 wheel. This backend typically provides better performance than eigen backend. For prev..."

2024-06-07 15:26 UTC, RamaMalladiAWS commented on machinelearning/tensorflow.md
> +As of May 2024, Docker hub images from armswdev are based on TensorFlow 2.15.1, but also include additional downstream optimizations and experimental features. These are avaiable for trying out the e
redundant, can delete:
"These are avaiable for trying out the experimental downstream features and provide early feedback."

2024-06-07 15:27 UTC, RamaMalladiAWS commented on machinelearning/tensorflow.md
> +# For TensorFlow versions older than 2.14.0, the default runtime backend is Eigen, but typically onednn+acl provides better performance and this can be enabled by setting the below TF environment var
This was mentioned above too. Can delete?

2024-06-07 15:31 UTC, RamaMalladiAWS commented on machinelearning/tensorflow.md
> +wget https://github.com/bazelbuild/bazel/releases/download/<bazelversion>/bazel-<bazelversion>-linux-arm64
Can you add a step to define `bazelversion`?

2024-06-07 15:31 UTC, RamaMalladiAWS commented on machinelearning/tensorflow.md
> +wget https://github.com/bazelbuild/bazel/releases/download/<bazelversion>/bazel-<bazelversion>-linux-arm64
Can you add a step to define `bazelversion`?

2024-06-07 15:33 UTC, RamaMalladiAWS commented on machinelearning/tensorflow.md
> +export TF_ENABLE_XLA=0
is it required? shoud be set to `0`?

2024-06-07 15:34 UTC, RamaMalladiAWS commented on machinelearning/tensorflow.md
> +./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./wheel-TF<version>-aarch64
can you add a step to define `version`?

2024-06-07 15:37 UTC, RamaMalladiAWS commented on machinelearning/tensorflow.md
> +clang --version
The below steps are repeat of what we have under `gcc`. Possibly you can combine?

2024-06-07 15:39 UTC, RamaMalladiAWS requested changes
Looks good, some changes I have suggested.

2024-06-20 03:01 UTC, snadampal commented
@CristianPrundeanu , @RamaMalladiAWS , thanks for the review and suggestion. I have updated the PR.

2024-06-20 10:52 UTC, RamaMalladiAWS approved these changes

2024-06-20 11:53 UTC, merged